### PR TITLE
Added to light if the light is on or off

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>
# 🎉 New feature

## Summary

Related with:
 - Issues: Related with this issue https://github.com/ignitionrobotics/ign-gazebo/issues/638
 - PR https://github.com/ignitionrobotics/ign-gazebo/pull/1343

This will allow to define if a light is on or off.

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Review by nkoenig — APPROVED** [review]

**Comment by nkoenig** [comment]
I'm having second thoughts on  this. An intensity value of zero is effectively `off`. Is it possible to use the existing `intensity` field instead of creating a new field?

**Comment by ahcorde** [comment]
> I'm having second thoughts on this. An intensity value of zero is effectively `off`. Is it possible to use the existing `intensity` field instead of creating a new field?

This value allows you to turn on and off for a specific value of intensity, otherwise you need to set to zero the intensity and then restore or add a new value to the intensity. 

I don't know if this is a good reason to add a new value.

**Comment by nkoenig** [comment]
> > I'm having second thoughts on this. An intensity value of zero is effectively `off`. Is it possible to use the existing `intensity` field instead of creating a new field?
> 
> This value allows you to turn on and off for a specific value of intensity, otherwise you need to set to zero the intensity and then restore or add a new value to the intensity.
> 
> I don't know if this is a good reason to add a new value.

That's a good point. I'm okay with this.

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-25-fortress-edifice-citadel/1343/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-04-13-fortress-edifice/1367/1

**Pull request merged**
