### PR TITLE
Create CODEOWNERS with azeey and scpeters

### PR DESCRIPTION
**Pull request by scpeters**
Signed-off-by: Steve Peters <scpeters@openrobotics.org>

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
:tada: 

Each rule needs to be in one line, see https://github.com/ignitionrobotics/ign-gui/pull/251 and https://github.com/ignitionrobotics/ign-cmake/pull/155

**Comment by scpeters** [comment]
> 🎉
> 
> Each rule needs to be in one line, see [ignitionrobotics/ign-gui#251](https://github.com/ignitionrobotics/ign-gui/pull/251) and [ignitionrobotics/ign-cmake#155](https://github.com/ignitionrobotics/ign-cmake/pull/155)

https://github.com/ignitionrobotics/sdformat/pull/650/commits/d733e7aa678438074a3a9103a31fe467d61bd9bc

**Review by chapulina — APPROVED** [review]

**Review by azeey — APPROVED** [review]

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-01-10/1228/1

**Comment by osrf-triage** [comment]
This pull request has been mentioned on **Gazebo Community**. There might be relevant details there:

https://community.gazebosim.org/t/new-ignition-releases-2022-03-25-fortress-edifice-citadel/1343/1

**Pull request merged**
