### PR TITLE
Add triage, remove ticket templates

### PR DESCRIPTION
**Pull request by chapulina**
# 🎉 New feature

## Summary

* Removing the templates added in https://github.com/ignitionrobotics/sdformat/pull/486/ in favor of the ones in https://github.com/ignitionrobotics/.github/.
* Added the triage workflow for the [Core development board](https://github.com/orgs/ignitionrobotics/projects/3).

## Test it

After this is in, new tickets will show up at the inbox, and the ticket templates will be pulled from the org.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Code check passed (In source directory, run `sh tools/code_check.sh`)
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review
[another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+)
to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge**

🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸🔸

### CODE REVIEW

**Review by jennuine — APPROVED** [review]
LGTM, should this target `sdf9` then ported to `sdf11`?

**Comment by chapulina** [comment]
> should this target sdf9 then ported to sdf11

I almost did that initially, but I think that it only picks up the default branch, which is `sdf11` at the moment, so I think it's enough to merge forward from here.

**Comment by chapulina** [comment]
@osrf-jenkins run tests?

**Comment by chapulina** [comment]
I enabled the DCO bot after this PR was open. Let's merge without that check for now, reopening the PR would trigger lots of builds.

**Pull request merged**
