### PR TITLE
Bumps in garden: use ign-math7

### PR DESCRIPTION
**Pull request by chapulina**
* Part of https://github.com/ignition-tooling/release-tools/issues/574
* Builds on top of #805

### CODE REVIEW

**Comment by scpeters** [comment]
looks like a compilation error with ign-math7

**Comment by chapulina** [comment]
> looks like a compilation error with ign-math7

It builds for me locally with https://github.com/ignitionrobotics/ign-math/pull/342, but the CI error seemed different. Let's see this new round.

**Comment by scpeters** [comment]
there are test failures related to `-0` in quaternion streams

**Comment by scpeters** [comment]
> there are test failures related to `-0` in quaternion streams

I believe this is a behavior change with ign-math7 from https://github.com/ignitionrobotics/ign-math/pull/206

**Comment by chapulina** [comment]
> It builds for me locally with ignitionrobotics/ign-math#342, but the CI error seemed different. Let's see this new round.

Humm it still fails on Ubuntu

```
2021-12-27T19:15:10.4098630Z In file included from /github/workspace/src/Ellipsoid.cc:18:
2021-12-27T19:15:10.4099822Z /github/workspace/include/sdf/Ellipsoid.hh:20:10: fatal error: ignition/math/Ellipsoid.hh: No such file or directory
2021-12-27T19:15:10.4100715Z  #include <ignition/math/Ellipsoid.hh>
2021-12-27T19:15:10.4101593Z           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by scpeters** [comment]
> > It builds for me locally with [ignitionrobotics/ign-math#342](https://github.com/ignitionrobotics/ign-math/pull/342), but the CI error seemed different. Let's see this new round.
> 
> Humm it still fails on Ubuntu CI, with both Bionic and Focal
> 
> ```
> 2021-12-27T19:15:10.4098630Z In file included from /github/workspace/src/Ellipsoid.cc:18:
> 2021-12-27T19:15:10.4099822Z /github/workspace/include/sdf/Ellipsoid.hh:20:10: fatal error: ignition/math/Ellipsoid.hh: No such file or directory
> 2021-12-27T19:15:10.4100715Z  #include <ignition/math/Ellipsoid.hh>
> 2021-12-27T19:15:10.4101593Z           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

I think that build started before the nightlies were rebuilt

**Comment by chapulina** [comment]
This PR now builds on top of #805

**Comment by chapulina** [comment]
Now we need https://github.com/ignitionrobotics/ign-math/pull/235 merged forward, CC @scpeters 

```
/home/chapulina/dev_focal/ws_garden/src/sdformat/src/World.cc: In member function _sdf::v13::ElementPtr sdf::v13::World::ToElement() const_:
/home/chapulina/dev_focal/ws_garden/src/sdformat/src/World.cc:836:55: error: cannot convert _ignition::math::v7::SphericalCoordinates::Surfa
ceType_ to _const string&_ {aka _const std::__cxx11::basic_string<char>&_}
  836 |           this->dataPtr->sphericalCoordinates->Surface()));
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       ignition::math::v7::SphericalCoordinates::SurfaceType
```

**Comment by scpeters** [comment]
> Now we need [ignitionrobotics/ign-math#235](https://github.com/ignitionrobotics/ign-math/pull/235) merged forward, CC @scpeters
> 
> ```
> /home/chapulina/dev_focal/ws_garden/src/sdformat/src/World.cc: In member function _sdf::v13::ElementPtr sdf::v13::World::ToElement() const_:
> /home/chapulina/dev_focal/ws_garden/src/sdformat/src/World.cc:836:55: error: cannot convert _ignition::math::v7::SphericalCoordinates::Surfa
> ceType_ to _const string&_ {aka _const std::__cxx11::basic_string<char>&_}
>   836 |           this->dataPtr->sphericalCoordinates->Surface()));
>       |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
>       |                                                       |
>       |                                                       ignition::math::v7::SphericalCoordinates::SurfaceType
> ```

https://github.com/ignitionrobotics/ign-math/pull/344

**Review by scpeters — APPROVED** [review]

**Pull request merged**
