### PR TITLE
🎈 12.0.0

### PR DESCRIPTION
**Pull request by azeey**
# 🎈 Release

Preparation for 12.0.0 release.

Comparison to 11.3.0: https://github.com/ignitionrobotics/sdformat/compare/sdformat11_11.3.0...sdf12

Target new branch `sdf12`

## Checklist
- [x] Asked team if this is a good time for a release
- [x] There are no changes to be ported from the previous major version
- [x] No PRs targeted at this major version are close to getting in
- [x] Bumped minor for new features, patch for bug fixes
- [x] Updated changelog
- [x] Updated migration guide (as needed)
- [x] Link to PR updating dependency versions in appropriate repository in [ignition-release](https://github.com/ignition-release) (as needed): <LINK>

**Note to maintainers**: Remember to use **Squash-Merge**

### CODE REVIEW

**Comment by azeey** [comment]
@scpeters  Have we resolved the issue with armhf builds from https://github.com/ignition-tooling/release-tools/issues/421#issuecomment-813834795?

**Comment by chapulina** [comment]
> Have we resolved the issue with armhf builds

Just a note that this isn't a blocker for the release, our officially supported platforms are listed here: https://ignitionrobotics.org/docs/fortress

Also worth pointing out that we treat arm64 as a "tier 2" platform and wouldn't block the release for that either.

**Review by chapulina — APPROVED** [review]

**Comment by scpeters** [comment]
@osrf-jenkins run tests please

**Comment by scpeters** [comment]
> @scpeters Have we resolved the issue with armhf builds from [ignition-tooling/release-tools#421 (comment)](https://github.com/ignition-tooling/release-tools/issues/421#issuecomment-813834795)?

all the armhf builds worked fine for 12.0.0!

**Pull request merged**
